language: generic

services:
  - docker

install: true

script:
  - docker build -t mrplum/portfolio .
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push mrplum/portfolio:latest

before_deploy:
  script: ./scripts/publish.sh
  on:
    branch: master

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: master