language: generic

services:
  - docker

install: true

before_install:
  - bash ./scripts/update_docker.sh

jobs:
  include:
    - stage: Build Docker Image And Publish Artifact
      script: docker build -t mrplum/portfolio:latest -t mrplumb/portfolio:$BUILD_NUMBER .
      deploy:
        provider: script
        script: bash ./scripts/publish.sh

    - stage: Deploy to VPS
      script: bash ./scripts/deploy.sh
