language: generic

services:
  - docker

install: true

  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push mrplum/portfolio:latest

jobs:
  include:
    - stage: Build Docker Image 
      script: docker build -t mrplum/portfolio .
    - stage: Publish Artifact
      script: bash ./scripts/publish.sh
    - stage: Deploy to VPS
      script: bash ./scripts/deploy.sh
