language: generic

services:
  - docker

install: true

before_install:
  - './scripts/update_docker.sh'

jobs:
  include:
    - stage: Check Docker Version
      script: docker version

    - stage: Build Docker Image And Publish Artifact
      script: docker build -t mrplum/portfolio .
      deploy:
        provider: script
        script: bash ./scripts/publish.sh

    - stage: Deploy to VPS
      script: bash ./scripts/deploy.sh

# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# - docker push mrplum/portfolio:latest
