language: generic

services:
  - docker

addons:
  apt:
    packages:
    - sshpass

install: true

before_install:
  - bash ./scripts/update_docker.sh

jobs:
  include:
    - stage: Build Docker Image And Publish Artifact
      script: docker build -t mrplum/portfolio .
      deploy:
        provider: script
        script: bash ./scripts/publish.sh

    - stage: Deploy to VPS
      script: bash ./scripts/deploy.sh
