version: '3'

services:
  portfolio:
    image: mrplum/portfolio:latest
    container_name: portfolio
    restart: always
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.portfolio.frontend.rule=Host: www.sadanmallhi.com, sadanmallhi.com"
      - "traefik.portfolio.ports=9000"

networks:
  web:
    external: true
